// Catalogue de la plateforme : 24 jeux, 7 catégories.
// C'est la source de vérité des métadonnées (copie statique côté client
// pour l'affichage immédiat, endpoint GET /api/catalog pour le serveur).
import { Category, Difficulty, GameFamily, GameType } from "../types";

export interface GameCatalogEntry {
  type: GameType;
  name: string;
  category: Category;
  tagline: string;
  description: string;
  glyph: string;
  family: GameFamily;
  scoringEnabled: boolean;
  cardType: string; // filtre sur GameCard.type ; "MIXED" = plusieurs types
  options: string[]; // options par défaut (jeux "question" standard)
  roundsByDifficulty: Record<Difficulty, number>;
}

export const CATEGORIES_ORDER: Category[] = [
  "CONNAISSANCE",
  "ACTION_VERITE",
  "FUN",
  "ROMANTIC",
  "PROFOND",
  "FLIRT",
  "COMPETITION",
];

export const CATEGORY_LABELS: Record<Category, string> = {
  CONNAISSANCE: "Connaissance",
  ACTION_VERITE: "Action & Vérité",
  FUN: "Fun",
  ROMANTIC: "Romantique",
  PROFOND: "Profond",
  FLIRT: "Flirt",
  COMPETITION: "Compétition",
};

export const CATEGORY_GLYPHS: Record<Category, string> = {
  CONNAISSANCE: "🧠",
  ACTION_VERITE: "🎭",
  FUN: "😂",
  ROMANTIC: "🌹",
  PROFOND: "🌌",
  FLIRT: "🔥",
  COMPETITION: "🏆",
};

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  SOFT: "Doux",
  NORMAL: "Normal",
  INTENSE: "Intense",
};

export const DIFFICULTY_GLYPHS: Record<Difficulty, string> = {
  SOFT: "🟢",
  NORMAL: "🟡",
  INTENSE: "🔴",
};

const ROUNDS: Record<Difficulty, number> = { SOFT: 10, NORMAL: 15, INTENSE: 20 };

export const GAME_CATALOG: GameCatalogEntry[] = [
  {
    type: "GUESS_ME",
    name: "À quel point tu me connais ?",
    category: "CONNAISSANCE",
    tagline: "Devine mes goûts, mes rêves, mes habitudes.",
    description: "Questions sur l'un de vous : l'autre doit deviner sa réponse. Réponses simultanées, révélées ensemble.",
    glyph: "💞",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "GUESS_MY_ANSWER",
    name: "Devine ma réponse",
    category: "CONNAISSANCE",
    tagline: "Pense comme moi, réponds comme moi.",
    description: "Sur des cas concrets, trouve la réponse que ton/ta partenaire donnerait vraiment.",
    glyph: "🎯",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "WHO_KNOWS_BEST",
    name: "Qui connaît le mieux l'autre ?",
    category: "CONNAISSANCE",
    tagline: "Duel de connaissances intimes.",
    description: "Mêmes questions, deux réponses : celui dont les réponses collent aux goûts de l'autre gagne des points.",
    glyph: "🥇",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "TRUTH_OR_DARE",
    name: "Action ou Vérité",
    category: "ACTION_VERITE",
    tagline: "Le classique, en version couple.",
    description: "Tour à tour, choisis : une vérité (osée) ou une action (mignonne). Toujours réversible : tu peux passer.",
    glyph: "⚖️",
    family: "TURN_BASED",
    scoringEnabled: true,
    cardType: "MIXED",
    options: ["TRUTH", "DARE"],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "TRUTH",
    name: "Vérité",
    category: "ACTION_VERITE",
    tagline: "100% confidences.",
    description: "Chaque tour te pose une question intime et honnête.",
    glyph: "🫣",
    family: "TURN_BASED",
    scoringEnabled: true,
    cardType: "TRUTH",
    options: ["TRUTH"],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "DARE",
    name: "Action",
    category: "ACTION_VERITE",
    tagline: "100% défis à faire.",
    description: "Chaque tour impose une petite action, tendre ou fun.",
    glyph: "🤸",
    family: "TURN_BASED",
    scoringEnabled: true,
    cardType: "DARE",
    options: ["DARE"],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "WHO_IS_MORE",
    name: "Qui de nous deux ?",
    category: "FUN",
    tagline: "Le miroir du couple.",
    description: "« Qui des deux… ? » Chacun donne son nom, on compare. Le rire est garanti quand vous vous trompez.",
    glyph: "🤔",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: ["MOI", "MON PARTENAIRE"],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "WOULD_YOU_RATHER",
    name: "Tu préfères ?",
    category: "FUN",
    tagline: "Dilemmes absurdes et débats animés.",
    description: "Deux options impossibles à départager. Comparez vos choix et assumez-les.",
    glyph: "🪄",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "NO_YES_NO",
    name: "Ni oui ni non",
    category: "FUN",
    tagline: "Réponds sans prononcer les mots interdits.",
    description: "Une question piège par tour. Interdit de dire « oui », « non » ou de grimacer !",
    glyph: "🚫",
    family: "TURN_BASED",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "MIME_PARTNER",
    name: "Mime ton partenaire",
    category: "FUN",
    tagline: "Imite sans rire, c'est mission impossible.",
    description: "Mime une situation ou une habitude de ton/ta partenaire. S'il/elle comprend, vous gagnez le tour.",
    glyph: "🎬",
    family: "TURN_BASED",
    scoringEnabled: true,
    cardType: "CHALLENGE",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "COMPLIMENT_CHALLENGE",
    name: "Compliment Challenge",
    category: "ROMANTIC",
    tagline: "Tendre la parole en 24 cartes.",
    description: "Chaque tour, une raison (trouvée ou à inventer) de dire quelque chose de doux.",
    glyph: "💐",
    family: "TURN_BASED",
    scoringEnabled: true,
    cardType: "CHALLENGE",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "OUR_MEMORIES",
    name: "Nos souvenirs",
    category: "ROMANTIC",
    tagline: "Revisitez vos plus beaux moments.",
    description: "Souvenirs à raconter, précis ou flous. Chacun complète ce que l'autre a oublié.",
    glyph: "📸",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "COMPLETE_THE_SENTENCE",
    name: "Complète ma phrase",
    category: "ROMANTIC",
    tagline: "« Depuis que je te connais… »",
    description: "Une phrase à terminer, deux fins possibles. Découvrez si vous terminez de la même façon.",
    glyph: "✍️",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "FIVE_THINGS",
    name: "5 choses que j'aime chez toi",
    category: "ROMANTIC",
    tagline: "Lâchez les compliments, un à cinq.",
    description: "Un thème, cinq choses à citer. L'exercice d'admiration le plus simple qui existe.",
    glyph: "✦",
    family: "TURN_BASED",
    scoringEnabled: false,
    cardType: "CHALLENGE",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "DEEP_QUESTIONS",
    name: "Questions profondes",
    category: "PROFOND",
    tagline: "Passez de « quoi de neuf ? » à « qui es-tu ? »",
    description: "Les grandes questions qui font avancer un couple.",
    glyph: "🌌",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "OUR_DREAMS",
    name: "Nos rêves",
    category: "PROFOND",
    tagline: "Projets, ambitions, rêves d'enfant.",
    description: "Parlez de ce que vous voulez vraiment dans la vie, sans jugement.",
    glyph: "☁️",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "OUR_FUTURE",
    name: "Notre futur",
    category: "PROFOND",
    tagline: "Construire demain, ensemble.",
    description: "Vos envies à deux : voyage, maison, famille, mode de vie.",
    glyph: "🔮",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "OUR_VALUES",
    name: "Nos valeurs",
    category: "PROFOND",
    tagline: "Ce qui ne se négocie pas.",
    description: "Famille, argent, liberté, foi… alignez vos principes.",
    glyph: "🛡️",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "FLIRT_QUESTIONS",
    name: "Questions de flirt",
    category: "FLIRT",
    tagline: "La flamme, entretenue.",
    description: "Des questions canailles pour rallumer la tension.",
    glyph: "🔥",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "SEDUCTION_CHALLENGES",
    name: "Défis de séduction",
    category: "FLIRT",
    tagline: "Des petits gestes qui font fondre.",
    description: "Un défi sensuel par tour, à faire maintenant ou à garder pour plus tard.",
    glyph: "🌶️",
    family: "TURN_BASED",
    scoringEnabled: false,
    cardType: "CHALLENGE",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "IMPOSSIBLE_CHOICE",
    name: "Choix impossible",
    category: "FLIRT",
    tagline: "Si tu devais choisir…",
    description: "Un dilemme tordu, deux issues. Choisissez et découvrez vos failles.",
    glyph: "😈",
    family: "STANDARD",
    scoringEnabled: false,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "COUPLE_BATTLE",
    name: "Couple Battle",
    category: "COMPETITION",
    tagline: "Le duel du quotidien.",
    description: "Qui est le plus… ? Vous êtes d'accord = points pour le couple.",
    glyph: "⚔️",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: ["MOI", "MON PARTENAIRE"],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "TIMED_QUIZ",
    name: "Quiz chronométré",
    category: "COMPETITION",
    tagline: "90 secondes pour être sur la même longueur.",
    description: "Le rythme monte : répondez vite, comparez, validez.",
    glyph: "⏱️",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
  {
    type: "SPEED_DUEL",
    name: "Duel de rapidité",
    category: "COMPETITION",
    tagline: "Questions éclair, verdicts instantanés.",
    description: "Enchaînez les questions courtes. Celui qui hésite doit valider la réponse de l'autre.",
    glyph: "🌩️",
    family: "STANDARD",
    scoringEnabled: true,
    cardType: "QUESTION",
    options: [],
    roundsByDifficulty: ROUNDS,
  },
];

export function getCatalogEntry(type: GameType): GameCatalogEntry {
  const entry = GAME_CATALOG.find((g) => g.type === type);
  if (!entry) throw new Error(`Game inconnu dans le catalogue: ${type}`);
  return entry;
}